auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: HuangYan 
url: http://yan316.github.io
feed: /atom.xml
author_info: <a href="http://yan316.github.io">HuangYan</a>
